stages:
  - build
  - test
  - pages
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
  policy: pull-push

variables:
  CARGO_INCREMENTAL: 0
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  RUSTUP_HOME: /usr/local/rustup
  CLIPPY_OPTS: -W clippy::pedantic -A clippy::must_use_candidate -A clippy::doc_markdown -A clippy::empty_enum -A clippy::module_name_repetitions -A clippy::missing_errors_doc -A clippy::cast_possible_wrap

default:
  image: rust:buster

build:stable:
  stage: build
  before_script:
    - apt-get update -qy
    - apt-get -qy install libpam0g-dev llvm clang libclang-dev
  script:
    - cargo build --workspace --all-features --color=always
  artifacts:
    public: false
    paths:
      - target/debug/
    expire_in: 1 day

test:stable:
  stage: test
  needs:
    - build:stable
  dependencies:
    - build:stable
  before_script:
    - apt-get update -qy
    - apt-get -qy install libpam0g-dev llvm clang libclang-dev
    - cargo install cargo-hack
    - wget https://grenz-bonn.de/rust2junit.py
    - chmod +x rust2junit.py
  script:
    - cargo hack check --workspace --feature-powerset --no-dev-deps --color=always
    - cargo test --workspace --all-features --verbose | ./rust2junit.py
  artifacts:
    public: false
    expire_in: 1 week
    reports:
      junit: junit.xml

coverage:
  stage: test
  needs:
    - build:stable
  dependencies:
    - build:stable
  before_script:
    - apt-get update -qy
    - apt-get -qy install libpam0g-dev llvm clang libclang-dev
    - rustup toolchain install nightly
    - rustup default nightly
    - cargo install cargo-llvm-cov
  script:
    - cargo llvm-cov clean
    - cargo llvm-cov --doctests --html --hide-instantiations --remap-path-prefix
    - COVERAGE=$(grep '</table>' target/llvm-cov/html/index.html | sed 's#.*<pre>\s*\([0-9.%]*\)\s[^<>]*</pre></td><td[^<>]*><pre>[^<>]*</pre></td></tr></table>.*#\1#')
    - echo "Coverage:" $COVERAGE
  artifacts:
    public: false
    paths:
      - target/llvm-cov/
    expire_in: 1 week

clippy:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get -qy install libpam0g-dev llvm clang libclang-dev
    - rustup component add clippy
    - cargo install gitlab_clippy
  script:
    - cargo clippy -- ${CLIPPY_OPTS}
  after_script:
    - 'cargo clippy --message-format=json -- ${CLIPPY_OPTS} | ${CARGO_HOME}/bin/gitlab-clippy > gl-code-quality-report.json'
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 week
  only:
    - master
  needs: []

pages:
  stage: pages
  only:
    - master
  needs:
    - coverage
  dependencies:
    - coverage
  before_script:
    - apt-get update -qy
    - apt-get -qy install libpam0g-dev llvm clang libclang-dev
  script:
    - cargo doc --workspace --all-features --color=always
    - rm -rf public || true
    - mkdir public
    - cp -R target/doc/* public
    - cp -R target/llvm-cov public/
    - mv public/llvm-cov/html public/cov
    - rm -r public/llvm-cov
  artifacts:
    paths:
      - public

publish:
  stage: deploy
  dependencies: []
  when: manual
  needs:
    - "test:stable"
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]/
  script:
    - cargo publish --no-verify
