stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
  policy: pull-push

variables:
  CARGO_INCREMENTAL: 0
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

default:
  image: rustdocker/rust:stable

build:stable:
  stage: build
  script:
    - cargo build --workspace --all-features --color=always
  artifacts:
    public: false
    paths:
      - target/debug/
    expire_in: 1 day

test:stable:
  stage: test
  dependencies:
    - build:stable
  before_script:
    - apt-get -qy install libpam-runtime
  script:
    - cargo check --workspace --all-features --color=always
    - cargo test --workspace --all-features --color=always --verbose --jobs 1

pages:
  stage: deploy
  only:
    - master
  script:
    - cargo doc --workspace --all-features --color=always
    - rm -rf public || true
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
      - public
