stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
  policy: pull-push

variables:
  CARGO_INCREMENTAL: 0
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

default:
  image: rust:buster

build:stable:
  stage: build
  script:
    - cargo build --workspace --all-features --color=always
  artifacts:
    public: false
    paths:
      - target/debug/
    expire_in: 1 day

pages:
  stage: build
  only:
    - master
  script:
    - cargo doc --workspace --all-features --color=always
    - rm -rf public || true
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
      - public

test:stable:
  stage: test
  needs:
    - build:stable
  dependencies:
    - build:stable
  before_script:
    - 'echo "deb http://deb.debian.org/debian/ sid main contrib" >> /etc/apt/sources.list'
    - apt-get update -qy
    - apt-get -qy install libpam0g-dev kcov
  script:
    - export RUSTFLAGS="-C link-dead-code -C inline-threshold=0"
    - cargo check --workspace --all-features --color=always
    - cargo test --workspace --all-features --color=always --verbose --jobs 1
    - kcov --verify
        --include-pattern=/rust-pam-client/
        --exclude-line='#[derive,pub struct'
        --exclude-region='#[cfg(test)]:#[cfg(testkcovstopmarker)]'
        target/cov
        target/debug/deps/pam_client-???????????????? --test-threads 1
    - COVERAGE=$(grep -Po 'covered":.*?[^\\]"' target/cov/index.js | grep "[0-9]*\.[0-9]" -o)
    - echo "Coverage:" $COVERAGE

publish:
  stage: deploy
  dependencies: []
  needs:
    - "test:stable"
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]/
  script:
    - cargo publish --no-verify
